# This is default nos3 config file.
# This config file contains essential information which is needed for bootstrapping.

# developers note: for development, set environment to `"dev"` and make a config.yml and .env beside your build.

# environment determines where and how to read secrets. (dev/prod)
# default is prod.
environment: "prod"

# minio_client specifies settings for the MinIO instance.
minio_client:
  endpoint: "localhost:9000"

# minio_uploader specifies settings for the MinIO uploader.
minio_uploader:
  # timeout_in_ms defines the maximum duration (in milliseconds) for requests to the MinIO API.
  timeout_in_ms: 5000

  # bucket specifies the default bucket name where files will be uploaded.
  bucket: "myapp-temp-uploads"

# db_config specifies settings for database
db_config:

  # db_name defines the name
  db_name: "nos3_db"

  # connection_timeout_in_ms defines the timeout for connecting to the database
  connection_timeout_in_ms: 30000

  # query_timeout_in_ms defines the timeout for querying to the database
  query_timeout_in_ms: 5000


# broker_config specifies settings for broker
broker_config:

  # queue_name defines the name
  queue_name: "blobs"

  # broker_config specifies settings for broker

# publisher_config specifies settings for message queue publisher
publisher_config:

  # timeout_in_ms defines the publishing timeout
  timeout_in_ms: 5000